### ISSUE TITLE
Battery Voltage Information

### ISSUE THREAD

**Issue by rajibshibly** [ropensci/tidyhydat#102]
Is it possible to view the Battery Voltage data from tidyhydat.

Sometimes the transmission error in flow and level values can be captured using battery voltage information. An example of how battery voltage graph appears is shown below:

![battery_volt](https://user-images.githubusercontent.com/39829190/41170572-710f7e70-6b27-11e8-8bdd-209c305922fd.png)

**Comment by boshek** [comment]
Does you have a public facing data source for this?

**Comment by rajibshibly** [comment]
From our Provincial site but not through water survey canada:Stn# - NF03OB0042


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Stn# - NF03OB0042


 |

 |

 |




    On Friday, June 8, 2018, 2:31:54 PM GMT-2:30, Sam Albers <notifications@github.com> wrote:  
 
 
Does you have a public facing data source for this?

**Comment by boshek** [comment]
Until this is a public facing data source it will have to stay out of tidyhydat.
