### ISSUE TITLE
Entropy Analysis with Hydat Flow data

### ISSUE THREAD

**Issue by rajibshibly** [ropensci/tidyhydat#106]
I was wondering how the tidyhydat flow values can be used for entropy computation to prioritize individual stations in a network.

I would appreciate if you can forward me to a working example.

**Comment by boshek** [comment]
Hi @rajibshibly - this type of request is beyond the scope of an issue in this repository. Please see the issue template. That said, we do not have a working example of this type of analysis. If you were to create one, I would certainly consider a pull request to incorporate as a vignette for the package.
