### ISSUE TITLE
Amount of data accessible with this pkg?

### ISSUE THREAD

**Issue by sckott** [ropensci/tidyhydat#128]
👋  as part of preparing an rOpenSci annual report, we're trying to estimate amount of data the various pkgs in our suite provide access to.

Do you have a sense for how much data (e.g., in GB) one can access through this pkg?  And whatever metric is most relevant for this data?

**Comment by boshek** [comment]
Hi @sckott 

This package accesses a 1.1 GB sqlite database and then realtime data at either 5 min, 15 min or hourly intervals for 2138 stations over a thirty day window. 

Does that help?

**Comment by sckott** [comment]
yeah, that works, thanks much
