### ISSUE TITLE
realtime_dd for longer data periods such as 60, 90 days

### ISSUE THREAD

**Issue by WatershedFlow** [ropensci/tidyhydat#137]
Hi there,

Currently function realtime_dd can download past 30 days.  I would suggest go for 60, or 90, or just let user to select data periods. I often find I need seasonal data such as from today (June 8) back to March, and so on. EC’s data is there, just a minor change would be very helpful.

Thanks so much

West

**Comment by boshek** [comment]
👋  @WatershedFlow. Can you point me to where you are seeing machine readable ECCC hydrometric data that extend beyond 30 days? The `realtime_dd` function currently sources that data from here: https://dd.weather.gc.ca/hydrometric/csv/BC/daily/

**Comment by WatershedFlow** [comment]
https://wateroffice.ec.gc.ca/report/real_time_e.html?stn=05AD026&mode=Graph&startDate=2018-12-08&endDate=2020-06-08&prm1=46&prm2=-1

Real-Time Hydrometric Data Graph for WATERTON RESERVOIR (05AD026) [AB]
![image](https://user-images.githubusercontent.com/54557989/84059810-6c844980-a978-11ea-9a1b-436db32f92b3.png)

**Comment by boshek** [comment]
Yeah I figured you were searching the Water Office. That unfortunately isn't machine readable. While it would be available via scraping, that isn't the intent of the water office (AFAIK) so I've resisted that approach. This is a very common issue for folks. I would suggest sending a message to ECCC requesting that more preliminary data be made available.

**Comment by WatershedFlow** [comment]
Sam,
Here is what I got from EC. It sounds a reasonable response, though I am not sure this is what you are looking for. I can provide the name who sent this email to me, so that you could contact with EC directly.
_______________________________________________________________
Thank you for your email. 
 
The current Real Time website goes back 18 months.  If you scroll down, you can change the date parameters and also other parameters.  I've included a screen shot of the area you can modify the dates and parameters.
 
Thank you,

XXXXX
Water Survey of Canada
Environment and Climate Change Canada / Government of Canada
ec.rhcmbsk-wscmbsk.ec@canada.ca

**Comment by boshek** [comment]
@WatershedFlow Sorry I am probably being obtuse. I am well aware of the fact that the data is available via the water office. However until that data is available via the datamart (i.e. machine readable) _or_ an open API, tidyhydat won't support scrapping the data from the Water Office.
