### ISSUE TITLE
Error with realtime_dd() function

### ISSUE THREAD

**Issue by ashjolly** [ropensci/tidyhydat#144]
I seem to be running into an issue using the realtime_dd() function. Currently I'm passing a string of realtime sites to this function. The function seems to get caught up on sites with missing data through an error that derives from differences in column data types. Throwing this error means that it disrupts data loops that depend on the function to grab data for a number of sites prior to performing some functions on them:

Specifically:
tidyhydat::realtime_dd(station_number = "08KH019")

* No hourly data found for 08KH019
* No daily data found for 08KH019
Error: Can't combine `..1$STATION_NUMBER` <logical> and `..2$STATION_NUMBER` <character>.

Hopefully this is sufficient data!

**Comment by boshek** [comment]
👋 @ashjolly 

Thanks for the report. Can you try installing using this command:

`remotes::install_github("ropensci/tidyhydat", ref = "fix-realtime")`

Let's see if that works.

**Comment by ashjolly** [comment]
Fix looks great!
Critically the fix doesn't pull an error message that would wreck a loop, and the dataframe it produces can be merged with stations with data. Looks good!
