### ISSUE TITLE
Using `download_hydat` without a keypress?

### ISSUE THREAD

**Issue by boshek** [ropensci/tidyhydat#164]
:wave: @rchlumsk. 

Great point. Definitely should have a parameter. I see you've started some work. I think it would be best to have a parameter called `ask` which is a logical with default being `TRUE`. That was it won't break any existing code. Why don't you open that fork into a pull request and we can get this sorted? 

### Discussed in https://github.com/ropensci/tidyhydat/discussions/163

<div type='discussions-op-text'>

<sup>Originally posted by **rchlumsk** September 21, 2021</sup>
Hi there, is there a good way to use the `download_hydat` function without the keypress? Adding a present answer as a parameter to the download function would be one option, but wondering if there is any workaround the keypress in the existing function.

For context I am trying to use tidyhydat to update the HYDAT database in an external program, and would like to simply force it to update the database without the download time warning and question at the keypress.

Thanks!
Rob</div>

**Comment by rchlumsk** [comment]
I think this can now be closed with #165
