### ISSUE TITLE
Library failing to import 

### ISSUE THREAD

**Issue by SteveCoss** [ropensci/tidyhydat#185]
**Describe the bug**
Get the following error when trying to import. I have been using the library without issue until now.
 "library(tidyhydat)
Error: package or namespace load failed for ‘tidyhydat’:
 .onAttach failed in attachNamespace() for 'tidyhydat', details:
  call: NULL
  error: no such table: VERSION"

Using within R/3.5.3-gnu9.1 on a super computer cluster. 

Thanks!

**Comment by boshek** [comment]
Hmmm... Can you post the `sessionInfo()`? Also that is a very old version of R at this point. I'm not surprised that you might be experiencing some issues. A `traceback()` would also be useful.

**Comment by SteveCoss** [comment]
Yeah, it definitely occurred to me that I might be trying to work with too old of a version. It's just strange that it was working before.
Here's Session info:
![image](https://user-images.githubusercontent.com/13835347/195235409-3aca3ff0-c007-4a53-9053-5461069bde15.png)
And Here's Traceback.

![image](https://user-images.githubusercontent.com/13835347/195235686-9ec61b87-9ff7-4eea-82b2-b960d76b8654.png)
Is there a version of R that tidyhydat is particularly stable on? I do have some other options. My big issue us I am using some other older packages too. It could easily be that I've arrived at incompatible dependencies.

Thanks for all your help!

**Comment by boshek** [comment]
Huh - very weird. I'm not sure exactly. One more thing. Can you post the result of this? A little more info:
`sessioninfo::session_info()`. I've been a little lazy with my versions so I am trying to see if this was a CRAN version or a GitHub version. 

tidyhydat usually is quite stable. I'm prepping a release to CRAN so there are a few changes here in GitHub. The CRAN release though usually only gets updated a few times a year.

**Comment by SteveCoss** [comment]
Sure thing.
![image](https://user-images.githubusercontent.com/13835347/195242286-72689f1d-f02b-4216-8b5d-9dd88fcbb789.png)
I'm wondering if there's an issue with my server R. They did some maintenance last night right after all this started. Might not have anything to do with your library. I am able to load my other installed libraries though.

**Comment by boshek** [comment]
Oops can you share that again with tidyhydat loaded?

**Comment by SteveCoss** [comment]
Hey @boshek ,
I was able to sort this out by removing: ~/.local/share/tidyhydat
I removed that directory, uninstalled and reinstalled tidyhydat and everything works fine again. I'm not sure what might have caused this, but I don't think it was tidyhydat. Thanks again for helping!
