### ISSUE TITLE
realtime_ws() marking all station inputs as not found

### ISSUE THREAD

**Issue by pausoto7** [ropensci/tidyhydat#204]
realtime_ws() no longer recognizes stations when input with new update as far as I can tell. I have tried many different stations and the result is always the same. e.g.  

> ws_08 <- tidyhydat::realtime_ws(
    station_number = c("08NL071", "08NM174"),     
    parameters = c(47, 5)

Error in tidyhydat::realtime_ws(station_number = c("08NL071", "08NM174"),  : 
  object '"08NM174"' not found

> flow_real_time <- tidyhydat::realtime_ws(
     station_number = "10MA003", 
     parameters = 47, 
     start_date = Sys.Date()-30, 
     end_date = Sys.Date()

Error in tidyhydat::realtime_ws(station_number = "10MA003", parameters = 47,  : 
  object '"10MA003"' not found

It was working fine earlier today until I updated all my packages including tidyhydat. So I suspect it has something to do with the tidyhydat update or its dependencies. 

Thanks!

**Comment by boshek** [comment]
@pausoto7 - I assume it is working for you again? It is working for me right now.
