### ISSUE TITLE
Error: lazy loading

### ISSUE THREAD

**Issue by njatel** [ropensci/tidyhydat#65]
```r
install.packages("remotes")
remotes::install_github("ropensci/tidyhydat")
```
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'Rcpp'
ERROR: lazy loading failed for package 'tidyhydat'

**Comment by boshek** [comment]
@njatel I'm unable to reproduce this error. Can you please provide your session info? Also it may be due to your library location - have you recently re-installed R or RStudio? Have you tried installing Rcpp itself then replicating the installation steps above?

**Comment by sckott** [comment]
worked for me too, though I had `Rcpp` installed already

**Comment by njatel** [comment]
works now (outside office firewalls).  thanks.
