### ISSUE TITLE
plotting data

### ISSUE THREAD

**Issue by njatel** [ropensci/tidyhydat#66]
Any suggestions on how best to plot daily flows combining historic and real time data?

```{r}
setwd("C:/Users/nelso/AppData/Local/tidyhydat/tidyhydat")
hy_daily_flows(station_number = "08NM146")
```
Generates a table: station number, date, parameter, value and symbol.  Only includes historic data.

**Comment by boshek** [comment]
@njatel - are you hoping to average out the time to get daily averages for the realtime data?

Something like this would work with some obvious modifications depending on what is being presented:
```
library(dplyr)
library(tidyhydat)
library(ggplot2)


clark_df <- bind_rows(
  hy_daily_flows(station_number = "08NM146"),
  realtime_dd(station_number = "08NM146") %>%
    mutate(Date = as.Date(Date)) %>%
    group_by(Date) %>%
    summarise(Value = mean(Value))
) 

ggplot(clark_df, aes(x = Date, y = Value)) +
  geom_point() 
```
