### ISSUE TITLE
tidyhydat error message

### ISSUE THREAD

**Issue by njatel** [ropensci/tidyhydat#82]
I get the error message:

Warning in install.packages :
  package ‘tidyhydat’ is not available (for R version 3.4.2)

RStudio - Version 1.0.143

**Comment by boshek** [comment]
@njatel 

Can please post the results of `devtools::session_info()` and also `getOption("repos")`?

Could also try installing the dev version using `devtools::install_github("ropensci/tidyhydat")`

`tidyhydat` only depends on R version 3.3.0 or higher so this is local issue. Let's try to figure it out.

**Comment by njatel** [comment]
Session info ------------------------------------------------------------
 setting  value                       
 version  R version 3.4.2 (2017-09-28)
 system   x86_64, mingw32             
 ui       RStudio (1.0.143)           
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Los_Angeles         
 date     2018-01-30                  

Packages ----------------------------------------------------------------
 package       * version date       source                       
 base          * 3.4.2   2017-10-20 local                        
 compiler        3.4.2   2017-10-20 local                        
 curl            3.0     2017-10-06 CRAN (R 3.4.2)               
 datasets      * 3.4.2   2017-10-20 local                        
 devtools        1.13.3  2017-08-02 CRAN (R 3.4.2)               
 digest          0.6.12  2017-01-27 CRAN (R 3.4.1)               
 fasstr        * 0.1.0   2018-01-30 Github (bcgov/fasstr@64f1513)
 git2r           0.19.0  2017-07-19 CRAN (R 3.4.3)               
 graphics      * 3.4.2   2017-10-20 local                        
 grDevices     * 3.4.2   2017-10-20 local                        
 httr            1.3.1   2017-08-20 CRAN (R 3.4.2)               
 knitr           1.17    2017-08-10 CRAN (R 3.4.2)               
 memoise         1.1.0   2017-04-21 CRAN (R 3.4.3)               
 methods       * 3.4.2   2017-10-20 local                        
 R6              2.2.2   2017-06-17 CRAN (R 3.4.1)               
 remotes         1.1.0   2017-07-09 CRAN (R 3.4.2)               
 RevoUtils     * 10.0.6  2017-10-17 local                        
 RevoUtilsMath * 10.0.1  2017-09-19 local                        
 rstudioapi      0.7     2017-09-07 CRAN (R 3.4.1)               
 stats         * 3.4.2   2017-10-20 local                        
 tools           3.4.2   2017-10-20 local                        
 utils         * 3.4.2   2017-10-20 local                        
 withr           2.0.0   2017-07-28 CRAN (R 3.4.2)  

```{r}
devtools::install_github("ropensci/tidyhydat")
```
Downloading GitHub repo ropensci/tidyhydat@master
from URL https://api.github.com/repos/ropensci/tidyhydat/zipball/master
Installing tidyhydat
"C:/PROGRA~1/MICROS~4/ROPEN~1/R-34~1.2/bin/x64/R" --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/nelson.jatel/AppData/Local/Temp/RtmpEXTf4M/devtools1908acdbb1/ropensci-tidyhydat-fad3aa9"  \
  --library="C:/Users/nelson.jatel/Documents/R/win-library/3.4"  \
  --install-tests 

ERROR: dependency 'cli' is not available for package 'tidyhydat'
* removing 'C:/Users/nelson.jatel/Documents/R/win-library/3.4/tidyhydat'
Installation failed: Command failed (1)

**Comment by boshek** [comment]
- Did you try installing `cli`?
- Is your package library local or on shared drive? 
- Also can you let me know what your default repo is?
- Lastly did you try simply updating R and trying again?

**Comment by boshek** [comment]
@njatel Anything further on this?
